# SPDX-FileCopyrightText: Â© 2024 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "whiteprints"
SPDX-PackageSupplier = "whiteprints <>"
